// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _sum_io_top_HH_
#define _sum_io_top_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "sum_io.h"

namespace ap_rtl {

struct sum_io_top : public sc_module {
    // Port declarations 6
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    sum_io_top(sc_module_name name);
    SC_HAS_PROCESS(sum_io_top);

    ~sum_io_top();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sum_io* StgValue_6_sum_io_fu_14;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > StgValue_6_sum_io_fu_14_ap_start;
    sc_signal< sc_logic > StgValue_6_sum_io_fu_14_ap_done;
    sc_signal< sc_logic > StgValue_6_sum_io_fu_14_ap_idle;
    sc_signal< sc_logic > StgValue_6_sum_io_fu_14_ap_ready;
    sc_signal< sc_logic > StgValue_6_sum_io_fu_14_sum_i_ap_ack;
    sc_signal< sc_lv<32> > StgValue_6_sum_io_fu_14_sum_o;
    sc_signal< sc_logic > StgValue_6_sum_io_fu_14_sum_o_ap_vld;
    sc_signal< sc_logic > StgValue_6_sum_io_fu_14_sum_i_blk_n;
    sc_signal< sc_logic > StgValue_6_sum_io_fu_14_sum_o_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > sum_fu_10;
    sc_signal< sc_lv<2> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_ST_fsm_state1;
    static const sc_lv<2> ap_ST_fsm_state2;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_1E;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_StgValue_6_sum_io_fu_14_ap_start();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
